/*----------------------------------------------------------
NextKey - The Modern Vietnamese Input Method Engine.
Based on OpenKey architecture.

Copyright (C) 2026 NextKey Project
Author: Mai Tan Phat
License: GPL (Inherited from OpenKey)
-----------------------------------------------------------*/

// This file includes the packfolder-generated resources and provides
// a single binding function. Only include resources.cpp here to avoid
// multiple definition linker errors.

#include "sciter-x-api.h"
#include "sciter-x-host-callback.h"

#ifdef NDEBUG
// Include packfolder-generated resources (Release only)
#include "../../../../../Resources/Sciter/resources.cpp"
#endif

// Bind embedded resources to Sciter archive
// Call this ONCE after LoadLibrary(sciter.dll) and before creating any Sciter windows
void BindSciterResources() {
#ifdef NDEBUG
    // 'resources' is the byte array generated by packfolder.exe
    sciter::archive::instance().open(aux::elements_of(resources));
#endif
}
